export const ADD_CHAPTER = 'ADD_CHAPTER';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_COOKBOOK_FAILURE = 'FETCH_COOKBOOK_FAILURE';
export const FETCH_COOKBOOK_SUCCESS = 'FETCH_COOKBOOK_SUCCESS';
